name: CommVault

#version: "3"
services:
    commvault-redis:
        container_name: commvault-redis
        ports:
            - 6379:6379
            - 8001:8001
        restart: unless-stopped
        logging:
            options:
                max-size: 1g
        environment:
            - REDIS_ARGS=--requirepass admin --save 60 1000 --appendonly yes --loglevel warning
            - REDISTIMESERIES_ARGS=RETENTION_POLICY=20
        image: redis/redis-stack:6.2.6-v17 # redis/redis-stack-server:6.2.6-v17
    
    commvault-accounts:
        container_name: commvault-accounts
        ports:
            - 8080:8080
        restart: unless-stopped
        environment:
          - SPRING_DATASOURCE_URL=
        logging:
            options:
                max-size: 1g
        depends_on:
            commvault-redis:
                condition: service_started
                restart: true
        image: shortthirdman-org/commvault-accounts:latest