name: CommVault

#version: "3"
services:
    redis:
        container_name: commvault-redis
        ports:
            - 6379:6379
            - 8001:8001
        restart: unless-stopped
        networks:
            - commvault-net
        logging:
            options:
                max-size: 1g
        environment:
            - REDIS_ARGS=--requirepass admin --save 60 1000 --appendonly yes --loglevel warning
            - REDISTIMESERIES_ARGS=RETENTION_POLICY=20
        image: redis/redis-stack:6.2.6-v17 # redis/redis-stack-server:6.2.6-v17
    
    commvault:
        container_name: commvault
        ports:
            - 8080:8080
        restart: unless-stopped
        networks:
            - commvault-net
        logging:
            options:
                max-size: 1g
        depends_on:
            redis:
                condition: service_started
                restart: true
        image: shortthirdman/commvault-accounts:latest

    # vault:
        # image: hashicorp/vault:latest
        # container_name: vault
        # environment:
          # - VAULT_ADDR=http://vault:8200
          # - VAULT_API_ADDR=http://vault:8200
          # - VAULT_CLUSTER_ADDR=http://vault:8201
          # - VAULT_LOG_LEVEL=debug
          # - VAULT_UI=true
        # volumes:
          # - ./vault-config/vault.hcl:/vault/config/vault.hcl
          # - vault-data:/vault/data
        # ports:
          # - "8200:8200"
          # - "8201:8201"
        # networks:
          # - commvault-net
        # command: "server"
        # restart: unless-stopped
        # cap_add:
          # - IPC_LOCK
     
networks:
  commvault-net:
    driver: bridge

# volumes:
  # vault-data: