name: Docker Image CI

on:
  push:
    branches: [ "main", "feature/**", "bugfix/**", "hotfix/**" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --rm --compress --file Dockerfile-prod --tag ${{ IMAGE_NAME }}:1.0.0-DEV.1
